In [1]:
import pandas as pd

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [8]:
data=pd.read_json('/content/drive/MyDrive/orders_etl.json')

In [21]:
data

,order_id,order_date,total_amount,customer,products
0,1,2024-01-10,200.5,"{'customer_id': 101, 'name': 'John Doe', 'emai...","[{'product_id': 'P01', 'name': 'Wireless Mouse..."
1,2,2024-01-12,150.0,"{'customer_id': 102, 'name': 'Jane Smith', 'em...","[{'product_id': 'P03', 'name': 'Laptop Stand',..."
2,3,2024-01-12,120.0,"{'customer_id': 103, 'name': 'Alice Johnson', ...","[{'product_id': 'P04', 'name': 'Gaming Headset..."
3,4,2024-01-13,300.5,"{'customer_id': 101, 'name': 'John Doe', 'emai...","[{'product_id': 'P01', 'name': 'Wireless Mouse..."
4,5,2024-01-14,180.0,"{'customer_id': 104, 'name': 'Bob Brown', 'ema...","[{'product_id': 'P03', 'name': 'Laptop Stand',..."
5,6,2024-01-14,250.0,"{'customer_id': 105, 'name': 'Sania', 'email':...","[{'product_id': 'P01', 'name': 'Wireless Mouse..."
6,7,2024-01-16,180.0,"{'customer_id': 106, 'name': 'Rohit', 'email':...","[{'product_id': 'P02', 'name': 'Bluetooth Keyb..."
7,8,2024-01-16,230.0,"{'customer_id': 107, 'name': 'Nina Patel', 'em...","[{'product_id': 'P01', 'name': 'Wireless Mouse..."
8,9,2024-01-17,310.0,"{'customer_id': 108, 'name': 'Tom Harris', 'em...","[{'product_id': 'P04', 'name': 'Gaming Headset..."
9,10,2024-01-18,130.0,"{'customer_id': 109, 'name': 'Eva Lee', 'email...","[{'product_id': 'P05', 'name': 'Desk Organizer..."
10,11,2024-01-18,250.0,"{'customer_id': 101, 'name': 'John Doe', 'emai...","[{'product_id': 'P04', 'name': 'Gaming Headset..."
11,12,2024-01-19,180.0,"{'customer_id': 103, 'name': 'Alice Johnson', ...","[{'product_id': 'P01', 'name': 'Wireless Mouse..."

In [23]:
import pandas as pd
import json
from google.colab import drive

drive.mount('/content/drive')

with open('/content/drive/MyDrive/orders_etl.json') as f:
    data = json.load(f)

def flatten(data):
    orders_data=[]
    for order in data:
        for product in order['products']:
            row_orders = {
                "order_id": order["order_id"],
                "order_date": order["order_date"],
                "total_amount": order["total_amount"],
                "customer_id": order["customer"]["customer_id"],
                "customer_name": order["customer"]["name"],
                "email": order["customer"]["email"],
                "address": order["customer"]["address"],
                "product_id": product["product_id"],
                "product_name": product["name"],
                "category": product["category"],
                "price": product["price"],
                "quantity": product["quantity"]
            }
            orders_data.append(row_orders)

    return pd.DataFrame(orders_data)

df_orders = flatten(data)

df_orders.head()

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,order_id,order_date,total_amount,customer_id,customer_name,email,address,product_id,product_name,category,price,quantity
0,1,2024-01-10,200.5,101,John Doe,johndoe@example.com,123 Main StSpringfield,P01,Wireless Mouse,Electronics,25.0,2
1,1,2024-01-10,200.5,101,John Doe,johndoe@example.com,123 Main StSpringfield,P02,Bluetooth Keyboard,Electronics,45.0,1
2,2,2024-01-12,150.0,102,Jane Smith,janesmith@example.com,456 Oak StSpringfield,P03,Laptop Stand,Electronics,75.0,1
3,3,2024-01-12,120.0,103,Alice Johnson,alicejohnson@example.com,789 Birch StSpringfield,P04,Gaming Headset,Electronics,60.0,2
4,4,2024-01-13,300.5,101,John Doe,johndoe@example.com,123 Main StSpringfield,P01,Wireless Mouse,Electronics,25.0,3

In [24]:
event={'Records': [{'eventVersion': '2.1', 'eventSource': 'aws:s3', 'awsRegion': 'us-east-1', 'eventTime': '2026-03-18T19:02:45.654Z', 'eventName': 'ObjectCreated:Put', 'userIdentity': {'principalId': 'A2KL5ZTIFC5UKR'}, 'requestParameters': {'sourceIPAddress': '71.205.149.187'}, 'responseElements': {'x-amz-request-id': 'JP5EG3Q9D006JKY1', 'x-amz-id-2': '/rqPCWmnY2AfRSGrshwQgNJcoKBsJ+GEx9zCsUJH95PCXogHN++OuTHlsVgXA1xGxghGXw13saYsXuGZDvTHQC2Bq7VzS9zN'}, 's3': {'s3SchemaVersion': '1.0', 'configurationId': '6df7a107-99b8-4674-b725-10d7d22d850f', 'bucket': {'name': 'data-fid', 'ownerIdentity': {'principalId': 'A2KL5ZTIFC5UKR'}, 'arn': 'arn:aws:s3:::data-fid'}, 'object': {'key': 'order_json_incoming/orders_etl.json', 'size': 6959, 'eTag': 'f8abff6dd94bfc7add8916ae91a16b60', 'sequencer': '0069BAF6D59A8FD257'}}}]}

In [30]:
bucket_name =event['Records'][0]['s3']['bucket']['name']

In [34]:
file_name=event['Records'][0]['s3']['object']['key']

In [32]:
bucket_name

'data-fid'

In [35]:
file_name

'order_json_incoming/orders_etl.json'